title: Design Site
logourl: /assets/img/logo.svg

layouts_dir:  ./_jekyll/_layouts
includes_dir: ./_jekyll/_includes
sass:
  sass_dir: ./_jekyll/_sass
exclude: ['LICENSE', 'README.md', 'Gemfile.lock', 'Gemfile', './_resources']

baseurl: "/pages/mamuso/sketch-designsite"
repository: https://github.com/mamuso/sketch-designsite

markdown: kramdown
gems:
- jemoji

